/**
 * BioShelter Studio - Ecosystem & Material Data Store
 * Comprehensive scientific dataset for regenerative bioshelters
 */

export const BIOMES = {
  temperate: {
    id: 'temperate',
    name: 'Temperate Continental',
    icon: '🌲',
    latitude: 45,
    avgSummerTemp: 26,
    avgWinterTemp: -6,
    solarIrradiance: 4.2, // kWh/m²/day annual avg
    annualRainfall: 950, // mm
    description: 'Distinct 4-season climate. Requires deep thermal mass, night insulation curtains, and ground-to-air heat transfer.'
  },
  arid: {
    id: 'arid',
    name: 'Arid / High Desert',
    icon: '🏜️',
    latitude: 34,
    avgSummerTemp: 38,
    avgWinterTemp: 2,
    solarIrradiance: 6.8,
    annualRainfall: 220,
    description: 'High solar gain with extreme diurnal temperature swings. Prioritizes evaporative misting cooling and maximum water capture.'
  },
  subarctic: {
    id: 'subarctic',
    name: 'Sub-Arctic / High Alpine',
    icon: '❄️',
    latitude: 58,
    avgSummerTemp: 18,
    avgWinterTemp: -22,
    solarIrradiance: 2.9,
    annualRainfall: 600,
    description: 'Severe winter cold and low winter sun angles. Requires earth-sheltered walipini design, triple glazing, and rocket mass heater backup.'
  },
  subtropical: {
    id: 'subtropical',
    name: 'Humid Subtropical',
    icon: '🌴',
    latitude: 28,
    avgSummerTemp: 33,
    avgWinterTemp: 12,
    solarIrradiance: 5.4,
    annualRainfall: 1400,
    description: 'High ambient humidity and warm winters. Requires high thermal chimney ventilation, shaded solar angles, and dehumidification.'
  },
  // UI-06 FIX: Indian biomes added for accurate local simulation
  tropical_monsoon: {
    id: 'tropical_monsoon',
    name: 'Tropical Monsoon (India / SE Asia)',
    icon: '🌧️',
    latitude: 23,
    avgSummerTemp: 36,
    avgWinterTemp: 18,
    solarIrradiance: 5.8,
    annualRainfall: 2200,
    description: 'Monsoon-dominated climate with extreme humidity peaks June–September. Requires aggressive natural ventilation, rainwater harvesting, and evaporative cooling. Winter is ideal growing season.'
  },
  semi_arid_deccan: {
    id: 'semi_arid_deccan',
    name: 'Semi-Arid Deccan Plateau (India)',
    icon: '🌵',
    latitude: 17,
    avgSummerTemp: 38,
    avgWinterTemp: 14,
    solarIrradiance: 6.2,
    annualRainfall: 550,
    description: 'Hot dry summers with mild winters. Highest solar potential in India. Prioritize earth-sheltered design, Badgir wind-catchers, and maximum rainwater capture during 3-month monsoon.'
  }
};

export const STRUCTURE_TYPES = {
  geodesic: {
    id: 'geodesic',
    name: 'Geodesic Bio-Dome (3V / 4V)',
    icon: '🌐',
    windResistance: 0.95,
    volumeToSurfaceRatio: 0.88,
    solarApertureFactor: 0.92,
    baseCostPerSqm: 165,
    description: 'Optimal aerodynamic stability and spherical thermal circulation. Perfect for high winds and snow loads.'
  },
  walipini: {
    id: 'walipini',
    name: 'Earth-Sheltered Walipini',
    icon: '🏔️',
    windResistance: 0.98,
    volumeToSurfaceRatio: 0.65,
    solarApertureFactor: 0.85,
    baseCostPerSqm: 140,
    description: 'Pit greenhouse utilizing constant subterranean thermal inertia (50-55°F / 10-13°C year-round).'
  },
  gothic_arch: {
    id: 'gothic_arch',
    name: 'High-Thermal Gothic Arch',
    icon: '🏛️',
    windResistance: 0.85,
    volumeToSurfaceRatio: 0.76,
    solarApertureFactor: 0.90,
    baseCostPerSqm: 125,
    description: 'Steep pitch sheds heavy snow efficiently while allowing tall multi-tiered perennial polycultures.'
  },
  passive_solar_leanto: {
    id: 'passive_solar_leanto',
    name: 'Passive Solar Lean-To Ark',
    icon: '📐',
    windResistance: 0.88,
    volumeToSurfaceRatio: 0.72,
    solarApertureFactor: 0.96,
    baseCostPerSqm: 150,
    description: 'Heavily insulated North/East/West berm walls with an angled high-efficiency South-facing glazing aperture.'
  }
};

export const GLAZING_MATERIALS = {
  etfe_triple: {
    id: 'etfe_triple',
    name: 'ETFE Triple-Cushion (Pneumatic)',
    rValue: 3.2,
    uValue: 1.8,
    lightTransmittance: 0.90,
    uvTransmission: 0.85,
    lifespanYears: 30,
    costPerSqm: 85
  },
  polycarbonate_twin: {
    id: 'polycarbonate_twin',
    name: '16mm Twin-Wall Polycarbonate',
    rValue: 2.1,
    uValue: 2.7,
    lightTransmittance: 0.78,
    uvTransmission: 0.10,
    lifespanYears: 15,
    costPerSqm: 42
  },
  diffused_tempered_glass: {
    id: 'diffused_tempered_glass',
    name: 'Anti-Reflective Solar Glass',
    rValue: 1.1,
    uValue: 5.2,
    lightTransmittance: 0.94,
    uvTransmission: 0.75,
    lifespanYears: 50,
    costPerSqm: 110
  },
  aerogel_insulated: {
    id: 'aerogel_insulated',
    name: 'Nanogel Insulated Translucent Poly',
    rValue: 5.0,
    uValue: 1.1,
    lightTransmittance: 0.65,
    uvTransmission: 0.05,
    lifespanYears: 25,
    costPerSqm: 145
  }
};

export const SPECIES_DATABASE = [
  {
    id: 'tilapia_nile',
    name: 'Nile Tilapia (Oreochromis niloticus)',
    category: 'aquatic',
    icon: '🐟',
    tempMin: 18,
    tempOptimal: 26,
    tempMax: 32,
    phRange: [6.5, 8.0],
    proteinContentPercent: 26,
    growthCycleDays: 180,
    feedConversionRatio: 1.4,
    wasteOutputRate: 0.04,
    yieldKgPerM3Year: 28,
    synergies: ['duckweed_lemna', 'spirulina_algae', 'heirloom_tomatoes', 'sweet_basil'],
    notes: 'Extremely resilient omnivore. Converts algae & duckweed into high-value protein and rich plant nutrients.'
  },
  {
    id: 'rainbow_trout',
    name: 'Rainbow Trout (Oncorhynchus mykiss)',
    category: 'aquatic',
    icon: '🐠',
    tempMin: 8,
    tempOptimal: 15,
    tempMax: 20,
    phRange: [6.8, 7.8],
    proteinContentPercent: 20,
    growthCycleDays: 240,
    feedConversionRatio: 1.1,
    wasteOutputRate: 0.035,
    yieldKgPerM3Year: 22,
    synergies: ['watercress', 'tavistock_kale'],
    notes: 'High-value cold-water species. Ideal for alpine/subarctic bioshelters with deep cooling loops.'
  },
  {
    id: 'freshwater_prawns',
    name: 'Malaysian Giant Prawn (Macrobrachium)',
    category: 'aquatic',
    icon: '🦐',
    tempMin: 22,
    tempOptimal: 29,
    tempMax: 34,
    phRange: [7.0, 8.5],
    proteinContentPercent: 22,
    growthCycleDays: 150,
    feedConversionRatio: 1.8,
    wasteOutputRate: 0.025,
    yieldKgPerM3Year: 12,
    synergies: ['duckweed_lemna', 'tilapia_nile', 'spirulina_algae'],
    notes: 'Benthic detritivore that cleans tank bottoms and adds high-tier culinary yield.'
  },
  {
    id: 'heirloom_tomatoes',
    name: 'Heirloom Vine Tomato',
    category: 'crop',
    icon: '🍅',
    parDLIRequired: 22,
    tempMin: 14,
    tempOptimal: 24,
    tempMax: 32,
    phRange: [5.8, 6.5],
    growthCycleDays: 90,
    caloriesPerKg: 180,
    yieldKgPerM2Year: 35,
    nitrogenDemand: 'high',
    synergies: ['sweet_basil', 'tilapia_nile', 'red_worms', 'ladybugs', 'mason_bees'],
    notes: 'Heavy nutrient consumer, perfect companion with basil to deter pests.'
  },
  {
    id: 'sweet_basil',
    name: 'Genovese Sweet Basil',
    category: 'crop',
    icon: '🌿',
    parDLIRequired: 14,
    tempMin: 16,
    tempOptimal: 25,
    tempMax: 35,
    phRange: [5.5, 6.5],
    growthCycleDays: 35,
    caloriesPerKg: 230,
    yieldKgPerM2Year: 24,
    nitrogenDemand: 'medium',
    synergies: ['heirloom_tomatoes', 'tilapia_nile', 'ladybugs'],
    notes: 'Fast-growing high-margin herb. Absorbs nitrates rapidly from aquaponic grow beds.'
  },
  {
    id: 'watercress',
    name: 'Perennial Watercress',
    category: 'crop',
    icon: '🌱',
    parDLIRequired: 12,
    tempMin: 8,
    tempOptimal: 18,
    tempMax: 26,
    phRange: [6.2, 7.2],
    growthCycleDays: 28,
    caloriesPerKg: 110,
    yieldKgPerM2Year: 30,
    nitrogenDemand: 'high',
    synergies: ['rainbow_trout', 'tilapia_nile'],
    notes: 'Superfood biofilter. Pulls excess potassium and iron from fish waste stream.'
  },
  {
    id: 'dwarf_citrus',
    name: 'Dwarf Meyer Lemon & Lime',
    category: 'crop',
    icon: '🍋',
    parDLIRequired: 26,
    tempMin: 6,
    tempOptimal: 23,
    tempMax: 32,
    phRange: [5.5, 6.5],
    growthCycleDays: 365,
    caloriesPerKg: 290,
    yieldKgPerM2Year: 18,
    nitrogenDemand: 'medium',
    synergies: ['red_worms', 'mason_bees'],
    notes: 'Perennial sub-canopy tree providing constant microclimate humidity and vitamin C.'
  },
  {
    id: 'tavistock_kale',
    name: 'Dino Tuscan Kale',
    category: 'crop',
    icon: '🥬',
    parDLIRequired: 14,
    tempMin: 4,
    tempOptimal: 18,
    tempMax: 28,
    phRange: [6.0, 7.0],
    growthCycleDays: 50,
    caloriesPerKg: 350,
    yieldKgPerM2Year: 28,
    nitrogenDemand: 'medium',
    synergies: ['rainbow_trout', 'red_worms'],
    notes: 'Cold-tolerant staple greens rich in calcium, iron, and antioxidant carotenoids.'
  },
  {
    id: 'strawberries_everbearing',
    name: 'Albion Everbearing Strawberries',
    category: 'crop',
    icon: '🍓',
    parDLIRequired: 18,
    tempMin: 10,
    tempOptimal: 22,
    tempMax: 28,
    phRange: [5.5, 6.2],
    growthCycleDays: 70,
    caloriesPerKg: 320,
    yieldKgPerM2Year: 16,
    nitrogenDemand: 'medium',
    synergies: ['sweet_basil', 'ladybugs', 'mason_bees'],
    notes: 'Vertical tower producer. Excellent vertical space utilization.'
  },
  {
    id: 'duckweed_lemna',
    name: 'Lemna Minor (Bio-Protein Duckweed)',
    category: 'crop',
    icon: '☘️',
    parDLIRequired: 10,
    tempMin: 12,
    tempOptimal: 26,
    tempMax: 33,
    phRange: [5.0, 8.5],
    growthCycleDays: 4,
    caloriesPerKg: 380,
    yieldKgPerM2Year: 90,
    nitrogenDemand: 'high',
    synergies: ['tilapia_nile', 'freshwater_prawns'],
    notes: 'Up to 40% crude protein dry weight. Closes the feed loop by feeding fish directly.'
  },
  {
    id: 'spirulina_algae',
    name: 'Spirulina Micro-Algae (Arthrospira)',
    category: 'crop',
    icon: '🧪',
    parDLIRequired: 20,
    tempMin: 20,
    tempOptimal: 35,
    tempMax: 40,
    phRange: [8.5, 10.5],
    growthCycleDays: 3,
    caloriesPerKg: 2900,
    yieldKgPerM2Year: 120,
    nitrogenDemand: 'high',
    synergies: ['tilapia_nile'],
    notes: '60% complete protein, dense in B12, iron, and phycocyanin. Highly efficient carbon sequesterer.'
  },
  {
    id: 'oyster_mushrooms',
    name: 'Pearl Oyster Mushrooms (Pleurotus)',
    category: 'fungi',
    icon: '🍄',
    tempMin: 12,
    tempOptimal: 20,
    tempMax: 28,
    phRange: [6.0, 7.5],
    growthCycleDays: 21,
    caloriesPerKg: 330,
    yieldKgPerM2Year: 45,
    co2ProductionRate: 0.12,
    synergies: ['heirloom_tomatoes', 'sweet_basil', 'red_worms'],
    notes: 'Grown on spent agricultural waste. Generates vital CO2 for accelerated plant photosynthesis.'
  },
  {
    id: 'red_worms',
    name: 'Red Wiggler Vermicompost (Eisenia fetida)',
    category: 'decomposer',
    icon: '🪱',
    tempMin: 10,
    tempOptimal: 22,
    tempMax: 30,
    phRange: [6.5, 7.5],
    growthCycleDays: 60,
    castingsYieldKgPerMonth: 35,
    synergies: ['oyster_mushrooms', 'dwarf_citrus', 'heirloom_tomatoes'],
    notes: 'Converts plant trimmings into microbial-rich vermicast and liquid worm tea.'
  },
  {
    id: 'mason_bees',
    name: 'Blue Orchard Mason Bees (Osmia)',
    category: 'beneficial',
    icon: '🐝',
    tempMin: 12,
    tempOptimal: 22,
    tempMax: 30,
    pollinationEfficiency: 0.98,
    synergies: ['strawberries_everbearing', 'dwarf_citrus', 'heirloom_tomatoes'],
    notes: 'Non-aggressive solitary pollinator with 120x the fruit-setting efficiency of honeybees.'
  },
  {
    id: 'ladybugs',
    name: 'Convergent Ladybugs (Hippodamia)',
    category: 'beneficial',
    icon: '🐞',
    tempMin: 15,
    tempOptimal: 25,
    tempMax: 32,
    predationRatePerDay: 50,
    synergies: ['sweet_basil', 'strawberries_everbearing', 'heirloom_tomatoes'],
    notes: 'Biological pest management against aphids, mites, and whiteflies.'
  }
];

export const PRESET_DESIGNS = {
  homestead_ark: {
    id: 'homestead_ark',
    name: 'Self-Sustaining Family Ark (85m²)',
    tagline: 'Year-round four-season food autonomy for 4-6 people',
    biome: 'temperate',
    structure: 'geodesic',
    glazing: 'etfe_triple',
    diameter: 10.4,
    height: 5.2,
    floorArea: 85,
    thermalMassLiters: 12000,
    aquaponicsVolumeM3: 6.5,
    solarPvKw: 8.5,
    batteryKwh: 24,
    gahtPipeLengthM: 120,
    rainCatchmentAreaM2: 120,
    activeSpecies: [
      'tilapia_nile',
      'heirloom_tomatoes',
      'sweet_basil',
      'tavistock_kale',
      'strawberries_everbearing',
      'duckweed_lemna',
      'oyster_mushrooms',
      'red_worms',
      'mason_bees',
      'ladybugs'
    ]
  },
  alpine_walipini: {
    id: 'alpine_walipini',
    name: 'Sub-Zero Alpine Walipini (120m²)',
    tagline: 'Deep-pit geothermal bioshelter for severe mountain freezes',
    biome: 'subarctic',
    structure: 'walipini',
    glazing: 'aerogel_insulated',
    diameter: 12.0,
    height: 4.5,
    floorArea: 120,
    thermalMassLiters: 24000,
    aquaponicsVolumeM3: 10.0,
    solarPvKw: 14.0,
    batteryKwh: 40,
    gahtPipeLengthM: 200,
    rainCatchmentAreaM2: 140,
    activeSpecies: [
      'rainbow_trout',
      'watercress',
      'tavistock_kale',
      'oyster_mushrooms',
      'red_worms',
      'strawberries_everbearing'
    ]
  },
  desert_oasis_dome: {
    id: 'desert_oasis_dome',
    name: 'Arid Oasis Permaculture Sanctuary (150m²)',
    tagline: 'Evaporative microclimate closed-loop oasis with high water conservation',
    biome: 'arid',
    structure: 'geodesic',
    glazing: 'diffused_tempered_glass',
    diameter: 13.8,
    height: 6.5,
    floorArea: 150,
    thermalMassLiters: 18000,
    aquaponicsVolumeM3: 12.0,
    solarPvKw: 18.0,
    batteryKwh: 50,
    gahtPipeLengthM: 220,
    rainCatchmentAreaM2: 180,
    activeSpecies: [
      'tilapia_nile',
      'freshwater_prawns',
      'spirulina_algae',
      'dwarf_citrus',
      'heirloom_tomatoes',
      'sweet_basil',
      'duckweed_lemna',
      'ladybugs'
    ]
  },
  urban_gothic_hub: {
    id: 'urban_gothic_hub',
    name: 'High-Density Commercial Gothic Hub (200m²)',
    tagline: 'Multi-tier vertical production for restaurant supply & community resilience',
    biome: 'subtropical',
    structure: 'gothic_arch',
    glazing: 'polycarbonate_twin',
    diameter: 16.0,
    height: 7.0,
    floorArea: 200,
    thermalMassLiters: 15000,
    aquaponicsVolumeM3: 16.0,
    solarPvKw: 22.0,
    batteryKwh: 60,
    gahtPipeLengthM: 180,
    rainCatchmentAreaM2: 240,
    activeSpecies: [
      'tilapia_nile',
      'freshwater_prawns',
      'heirloom_tomatoes',
      'sweet_basil',
      'watercress',
      'strawberries_everbearing',
      'spirulina_algae',
      'oyster_mushrooms',
      'red_worms',
      'mason_bees',
      'ladybugs'
    ]
  }
};
